### ISSUE TITLE
Начать

### ISSUE THREAD

**Issue by PolyProgrammist** [valera5505/SPbU#1]

**Comment by Ram6aldi** [comment]
Go

**Comment by Kn1MS** [comment]
Дратути

**Comment by Damir214** [comment]
Йоу
Верифай надо было сделать оказывается

**Comment by Ram6aldi** [comment]
# WoW

**Comment by Kn1MS** [comment]
# test

**Comment by Kn1MS** [comment]
![chrysanthemum](https://cloud.githubusercontent.com/assets/21951870/18202830/5620f6b4-711b-11e6-979d-1f8d912aa56e.jpg)
